collections:
  - name: "links"
    label: "Links"
    folder: "src/links"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Date", name: "date", widget: "datetime", required: true }
      - { label: "External URL", name: "external_url", widget: "string", required: true }
      - { label: "Body", name: "body", widget: "markdown" }

backend:
  name: github
  repo: dvdwinden/danielvdwww
  branch: main

media_folder: "src/assets"
public_folder: "/assets"

# Site info
site:
  title: "Daniël van der Winden"
  url: "https://daniel.pizza"